/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author danz
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
        lblTexto.setText("<html>Vou pensar em número de <strong>1 a 7<strong>. Tente adivinhar.<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblValor = new javax.swing.JSpinner();
        lblAdivinhe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        lblTexto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTexto.setText("texto");
        lblTexto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 72, 420, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, 40));

        lblValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, 30));

        lblAdivinhe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAdivinhe.setText("Advinhe");
        lblAdivinhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAdivinheActionPerformed(evt);
            }
        });
        getContentPane().add(lblAdivinhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAdivinheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAdivinheActionPerformed
        // TODO add your handling code here:
        double numero = 1 + Math.random() * (8-1);
        int valor = (int) numero;
        int resultado = Integer.parseInt(lblValor.getValue().toString());
        String r1 = "<html>Acertou!<html>";
        String r2 = "<html>Errou, eu pensei no valor " + valor + "<html>";
        
        String res = (valor==resultado)?r1:r2;
        lblTexto.setText(res);
    }//GEN-LAST:event_lblAdivinheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lblAdivinhe;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JSpinner lblValor;
    // End of variables declaration//GEN-END:variables
}
